config/routes.rb
MaterialTracker::Application.routes.draw do

  resources :vendor_questionnaire_groups
  resources :questionnaire_groups
  resources :questionairre_items
  post '/save_questionairre_answers' => 'questionairre_items#save_answer'
  post '/delete_answer' => 'questionairre_items#delete_answer'

  resources :groups
  match '*path' => 'application#options_for_mopd', :via => :options
  match '/popv_viewer' => 'sessions#login_as_popv_viewer'
  match '/inventory_items/tags' => 'inventory_items#tags'
  match '/inventory_items/edit_basket' => 'inventory_items#edit_basket'
  resources :general_references do
    collection do
      get :search
    end
    member do
      get :download
    end

  end
  
  resources :questions do
    collection do
      get :search
    end
    resources :question_answers
  end
  
  resources :questionnaires do
    collection do
      get :search
    end
  end

  resources :events
  resources :emails
  resources :cart_items
  resources :carts do
    collection do
      get :search
      get :recent_search
      put :issue
      get :get_order
      get :recent
    end

  end

  match '/get_order' => 'carts#get_order'
  resources :bills do

    member do
      post :approve
      post :review
      post :disapprove
      post :unreview
      get :request_for_quote_pdf
    end

  end

  resources :bill_items do
    collection do
      post :create_many
    end


  end

  match '/sext/save_tabs' => 'sext#save_tabs'
  match '/sext/tabs' => 'sext#tabs'
  match '/sext/:resource/' => 'sext#index', :via => :get
  match '/sext/:resource/store' => 'sext#store', :via => :get
  match '/sext/:resource/:id' => 'sext#show', :via => :get
  match '/sext/:resource/' => 'sext#create', :via => :post
  match '/sext/:resource/:id' => 'sext#update', :via => :put
  match '/sext/:resource/:id' => 'sext#destroy', :via => :delete
  match '/piping/clone_class/:id' => 'piping#clone_class'
  match '/piping/compare_piping_classes/:ids' => 'piping#compare_piping_classes', :format => 'json'
  match '/piping/compare_piping_classes.csv/:ids' => 'piping#compare_piping_classes', :format => 'csv'
  match '/orders/select_pos' => 'orders#select_pos'
  match '/piping_class_details/prepend_text_to_descriptions' => 'piping_class_details#prepend_text_to_descriptions', :via => :put
  match '/' => 'home#index'
  match '/menu' => 'home#menu', :as => :main_menu
  match '/superuser' => 'home#superuser'
  match '/changelog' => 'home#changelog'
  match '/warehouse' => 'orders#warehouse'
  match '/orders/add_line_item' => 'orders#add_line_item'
  match '/remote_client/:action' => 'remote_client#index'
  match '/remote_client/:action/:id' => 'remote_client#index'
  match '/material_requests/bill' => 'material_requests#bill', :as => :bill
  match '/material_requests/sample_csv' => 'material_requests#sample_csv', :as => :bill
  resources :record_changelogs do
    collection do
      post :update_comment
    end
    member do
      get :get_attachment
    end

  end

  resources :sessions
  resources :inventory_items do
    collection do
      get :search
    end


  end

  resources :companies do
    collection do
      get :search
    end


  end

  resources :units do
    collection do
      get :search
    end


  end

  resources :quotes do
    collection do
      get :search
    end


  end

  resources :bulk_changes do
    collection do
      post :tables
      post :fields
      post :search_results
      post :finalize_replace
    end


  end

  resources :boms do
    collection do
      get :search
      get :excel
    end


  end

  resources :piping do
    collection do
      get :search
      get :classes_service
      get :classes_only
      get :classes_only_incl_archived
      get :units_for_measure
      get :piping_sizes
      get :piping_class_details
      get :piping_components
      get :all_classes_pdf
      get :notes_pdf
    end
    member do
      get :details_pdf
      get :valves_pdf
      post :increase_order
      post :decrease_order
      post :increase_group_order
      post :decrease_group_order
    end

  end

  resources :piping_class_details do
    collection do
      get :search
    end
    member do
      put :add_note
    end

  end

  resources :piping_components do
    collection do
      get :search
      get :associated_piping_classes
    end


  end

  resources :piping_subcomponents do
    collection do
      get :search
    end


  end

  resources :piping_specifications do
    collection do
      get :search
    end


  end

  resources :piping_descriptions do
    collection do
      get :search
    end


  end

  resources :user_notes do
    collection do
      get :search
    end


  end

  resources :valve_components do
    collection do
      get :search
    end


  end

  resources :manufacturers do
    collection do
      get :search
    end


  end

  resources :piping_notes do
    collection do
      get :search
    end


  end

  match '/valves/clone/:id' => 'valves#clone'
  resources :valves do
    collection do
      get :search
      get :all_pdf
      get :comparison_pdf
      get :related_valve_components
      get :related_manufacturers
      get :related_old_manufacturers
      get :related_piping_classes
      get :related_piping_references
      get :valve_components
      get :pdf
      post :supersede_manufacturer
      post :undo_supersede_manufacturer
      post :add_manufacturer
      put :edit_manufacturer
      delete :delete_manufacturer
    end
    member do
      put :archive
    end

  end

  resources :popv do
    collection do
      get :search
      post :upload_reference_documents
      get :popv_user_guide
    end


  end

  resources :employees do
    collection do
      get :search
    end


  end

  resources :orders do
    collection do
      get :test
      get :search
      get :complete_vendor
    end
    member do
      get :complete_employee
    end

  end

  resources :reminders do
    collection do
      get :search
    end


  end

  resources :reference_number_types
  resources :vendors do
    collection do
      get :search
    end


  end

  resources :po_statuses do
    collection do
      get :search
    end


  end

  resources :vendor_groups do
    collection do
      get :search
    end


  end

  resources :material_requests do
    collection do
      get :search
    end
    member do
      get :update_items_from_request
      get :pdf
      get :acknowledge
      get :vendor_email
      get :new_from_bom
      get :duplicate
      get :duplicate_with_items
      get :get_purchaser_group
    end

  end

  resources :requested_line_items
  resources :piping_references
  resources :piping_reference_attachings do
    collection do
      post :create_with_piping_reference
    end


  end

  resources :tickets do
    collection do
      get :search
    end


  end

  resources :links
  match '/init-questionnaire/(:id)' => 'questionnaire_workflows#init_questionnaire', :as => :init_questionnaire_workflow
  match 'vendor-questionnaire/(:id)' => "questionnaire_workflows#show", :as => :show_question
  
  get 'vendor-answer-questionnaire/(:id)' => 'questionnaire_workflows#vendor_view', :as => :vendor_view
  post 'vendor-answer-questionnaire/(:id)' => 'questionnaire_workflows#vendor_answer', :as => :vendor_answer
  get 'approval/(:id)' => 'questionnaire_workflows#approval_view', :as => :approval_view
  post 'approval/(:id)' => 'questionnaire_workflows#approval', :as => :approval
  match 'completed-vendor-questionnaire/(:id)' => 'questionnaire_workflows#completed' , :as => :complete_vendor_questionnaire
  match 'application_approved/(:id)' => 'questionnaire_workflows#application_approved' , :as => :application_approved
  match '/signup' => 'employees#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/reports' => 'reports#index', :as => :reports
  match '/reports/email' => 'reports#email'
  match '/csv' => 'reports#csv', :as => :csv
  match '/contact_us' => 'home#contact_us', :as => :contact_us
  match '/docs' => 'application#docs'
  match '/admin/new_message' => 'admin/messages#new_admin_message'
  match '/admin/index_sphinx' => 'admin/utilities#index_sphinx'
  match '/:controller(/:action(/:id))'
  match ':controller/:action' => '#index'
  match ':controller' => '#index'

end

app/helpers/material_requests_helper.rb
module MaterialRequestsHelper

  def previous_quote(quote)
    q = quote.find_previous
    if q.nil?
      return img_button "Previous Quote", "previous.png", ""
    else
      m = q.material_request
    end
    if(m.nil?)
      return img_button "Previous Quote", "previous.png", ""
    else
      return img_button "Previous Quote", "previous.png", 
                url_for(:action => :quote, 
                  :id => m.id, 
                  :controller => :material_requests, 
                  :vendor_id => q.vendor_id, 
                  :access_key => q.vendor.access_key)
    end
  end

  def next_quote(quote)
    q = quote.find_next
    if q.nil?
      return img_button "Next Quote", "next.png", ""
    else
      m = q.material_request
    end
    if(m.nil?)
      return img_button "Next Quote", "next.png", ""
    else
      return img_button "Next Quote", "next.png", 
                url_for(:action => :quote, 
                  :id => m.id, 
                  :controller => :material_requests, 
                  :vendor_id => q.vendor_id, 
                  :access_key => q.vendor.access_key)
    end
  end

  def m_disabled?
    @material_request.disabled_for?(current_employee)
  end
  
  def m_disabled_then(string)
    m_disabled? ? string : ''
  end
  
  def filter_url(filter_hash = {})
    new_params = params.merge(filter_hash)
    
    url = "/material_requests/?"
    
    if new_params[:status]
      url += "&amp;status=" + new_params[:status].to_s
    end
    if new_params[:requester]
      url += "&amp;requester=" + new_params[:requester].to_s
    end
    if new_params[:unit]
      url += "&amp;unit=" + new_params[:unit].to_s
    end
    if new_params[:group]
      url += "&amp;group=" + new_params[:group].to_s
    end
    
    return url
  end
  
  def not_purchaser?
    !current_employee.admin? && !current_employee.purchasing?
  end
            
  def link_to_orders(material_request)
  	pos = material_request.orders
    pos.map do |po|
      "<span id=\"po_link_#{po.id}\">" +
          link_to("#" + po.po_no.to_s, edit_order_path(po), :id=>"order_#{po.id.to_s}") + 
	  if current_employee.admin?
	  
	      "<a onclick=\"if (confirm('Are you sure you want to remove all links to #{po.po_no.to_s} from this Request?')) { new Ajax.Request('/material_requests/remove_po_links/#{material_request.id}?po_id=#{po.id}', {asynchronous:true, evalScripts:true}); }; return false;\" href=\"#\">(x)</a>"
  	  else
  	  	""
  	  end
	end.join(", ").html_safe

  end

  def link_to_quotes(material_request)
    quotes = material_request.quotes
    material_request_id = material_request.id

    quotes.map do |quote|
      if(!quote.vendor.blank?)
        #if we're hiding pricing, get rid of extra
        if(ResourcePermission.is_enabled?(:hide_pricing))
          link_to(quote.vendor.name, url_for(:controller => "material_requests", :action => "quote", :vendor_id => quote.vendor_id, :access_key => quote.vendor.access_key, :id => material_request_id))
        else
          link_to(quote.vendor.name + quote.filled_count + " ($" + number_with_precision(quote.total_price, {:precision => 2}) + ")", url_for(:controller => "material_requests", :action => "quote", :vendor_id => quote.vendor_id, :access_key => quote.vendor.access_key, :id => material_request_id))
        end
      end
    end.join(", ").html_safe
  end

  def link_to_quotes_comparison(material_request)
      link_to("<span style='font-size:10px;'>Compare Quotes</span>".html_safe, url_for(:controller => "material_requests", :action => "quote_comparison", :id => material_request.id))
  end
end

app/views/material_requests/_links_to_orders.html.erb
<% if material_request.orders.size > 0 %>
<p class="clear">
	<strong style="font-weight: bold; font-size: 95%;">POs</strong>
<span id="links_to_orders"><%= link_to_orders material_request %></span>
</p>
<% end %>

app/views/material_requests/_new.html.erb
<%= render :partial => "pipe_materials", :locals => { :with_description => false} %>


<table class="information clear">
  <tr>
    <th style="width: 70px;">Qty.</th>
    <th style="width: 70px;">U/M.</th>
    <th>Description <span class="required" style="color: #ccc;">* required</span></th>
    <th style="width: 70px;">Class</th>
    <th style="width: 70px;">Details</th>
  </tr>
  
  <% fields_for :requested_line_item, RequestedLineItem.new do |i|%>
    <tr>
      <td style="padding: 4px;">
        <%= i.text_field :quantity %>
      </td>
      <td style="padding: 4px;">
        <%= i.text_field :unit_of_measure %>
      </td>
      <td style="padding: 4px;">
        <%= i.text_area :material_description, :style => "width: 99%;", :rows => 2, :id => 'pipe-builder-description' %>
      </td>
      <td style="padding: 4px;">
        <%= i.text_field :notes %>
      </td>
    </tr>    
  <% end %>
</table>

<p class="menu" style="float: right;">  
  <%= submit_tag "Submit Request" %> 
  <%= button_to_function "Request Pipe", "Effect.toggle('pipe_materials', 'appear', { duration : 0.2 })" %> 
  or <%= link_to_function "Cancel", "Effect.toggle('new_request_slide', 'appear', { duration : 0.1 })" %>
</p>

app/views/material_requests/_search.html.erb
<% if logged_in? and params[:action] != "quote" and params[:action] != "email_quote" %>
<%= form_tag search_material_requests_path, :method => :get do -%>
    <input type="text" value="Search Requests" onfocus="InterfaceHelper.clear(this);" onblur="InterfaceHelper.reset(this);" style="font-style: italic; color: gray; width: 180px;" name="q" />
    <% [:status, :group, :unit, :requester].each do |filter_param| %>
        <% if params.has_key?(filter_param) %>
            <input type="hidden" value="<%= params[filter_param] %>" name="<%= filter_param %>" />
        <% end %>
    <% end %>
<% end -%>
<% end %>

app/views/material_requests/email_quote.html.erb
<style type="text/css" media="screen">
    #vendor_filter { color: #888; font-style: italic; width: 240px;}
    #vendor_filter_submit {}
</style>

<div style="width: 100%;">
	
	<% if !@material_request.acknowledged? %>
		<div style="text-align: center; font-size: 110%; color: red; background-color: #fcc; border: 1px solid #f66; border-right: 2px solid #f77; border-bottom: 2px solid #f77; width: 70%; padding: 7px; margin-bottom: 12px;">
			This material request has not been <b>acknowledged</b> yet, are you sure you want to send out a quote?
			<span style="font-size: 80%;">
			<%= link_to "Back to Material Request", edit_material_request_path(@material_request) %>
			</span>
		</div>
	<% end %>
	
	<div style="float: left; width: 49%">
		<form id="mail" method="post" class="edit full" enctype="multipart/form-data">
		  <p>
		    <label>Message:</label>
		    <textarea name="message" style="width: 400px; height: 100px;"><%= params[:message] %></textarea>
		  </p>
		  <% if !@material_request.suggested_vendor.blank? %>
		  <p>
		    <label>Suggested Vendor:</label>
		    <%= @material_request.suggested_vendor %>
		  </p>
		  <% end %>
		  <div class="left"><label>Vendor Emails:</label></div>
		  <div class="right"><input type="checkbox" name="save_emails" value="1" /> Save emails</div>
		  <div id="vendor_emails" class="clear">
		      <% if !@suggested_vendor.blank? %>
		        <div class='v-email' id="vendor_mail_<%= @suggested_vendor.id %>">
		            <div class="left clear" style="text-align: right; font-size: 85%;"><%= @suggested_vendor.name %></div>
		            <div class="right">
		                <input type="text" name="emails[<%= @suggested_vendor.id %>]" class="text vendor-email" value="<%= @suggested_vendor.email %>" style="width: 60%" />
		            <a href="#" style="font-size: 85%" onclick="$(this).up('div').up('div').replace()">delete</a>
		            </div>
		        </div>
		      <% end %>
		  </div>
		  <p class="menu clear">
		  	<%= render :partial => "request_attachments_for_quote", :locals => { :material_request => @material_request} %>
  	  	  <div>

			  	<div id="file-upload-fields" style="margin-top: 50px;">
					<p class="menu">
						<label>Attach a File (Ex: Engineering Drawings):</label>
						<input type="file" name="uploaded_quote_attachments[]"/>
					</p>
				</div>
				<a href="#" id="add-file-link">Add Another File</a>
		  </div>
			
		</form>
	</div>
  
	<div class="right" style="float: left; width: 49%;">
		<form class="edit full" onsubmit="return false;">  
		      <p>
		          <input type="text" class="text inline" id="vendor_filter" value="Search Vendors" />
		          <input type="submit" value="Search" id="vendor_filter_submit" class="inline" />
		          <a href="#reset" id="vendor_filter_reset">Reset</a>
		      </p>
		      <p>
		      <label>Vendors:</label>     
		      <%= render :partial => "select_vendor", :locals => { :vendors => @vendors, :size => 10 } %>
		     </p>
		     <p>
		     <input type="button" value="&larr; Add Vendor" onclick="addVendor(); return false;" />
		     </p>
			 <p>
			 	<label>Select from vendor groups:</label>				
				<select size="10" id="uxVendorGroupDropDown" class="clear" ondblclick="addVendorGroup(); return false;">
				   <% @vendor_groups.each do |v| %>
				       <option id="vendor_group_<%= v.id %>" value="vendor_group_<%= v.id %>" title="<%= v.vendors[0..10].map{|vendor| vendor.name}.join(', ') %>" /><%= h v.name %> (<%= v.vendors.length %>)</option>
				   <% end %>
				</select>
				<script type="text/javascript">
					var vendorsOfVendorGroups = <%= @vendor_groups_for_js.to_json %>;
				</script>
			 </p>
			 <p>
			 	<div id="uxVendorGroupVendorsListPreview"></div>
			 </p>
			 <p>
			 	<input type="button" value="&larr; Add Vendor group" onclick="addVendorGroup(); return false;" />
			 </p>
		</form>
	</div>  
</div>

<script>
Telaeris.monitorAddFileLink("uploaded_quote_attachments");

Telaeris.vendorCounter = 0;

jQuery('#uxVendorGroupDropDown').change(function(){
	var groupMembersPreview = jQuery('#' + jQuery('#uxVendorGroupDropDown').val()).attr('title');
	if(vendorsOfVendorGroups[jQuery('#uxVendorGroupDropDown').val()].length > 10){
		groupMembersPreview = groupMembersPreview + "...";
	}
	jQuery('#uxVendorGroupVendorsListPreview').html(groupMembersPreview);
});
jQuery(document).ready(function(){
	if(jQuery('#uxVendorGroupDropDown').val() != null){
		jQuery('#uxVendorGroupDropDown').change();	
	}
});


function addVendor(){
    if(!$F('select')) return false;
    
    var select = $('select');
    var name = select.options[select.selectedIndex].innerHTML.unescapeHTML();
    var email = $F(select).match(/(.*) \(\d+\)$/).last().escapeHTML();
    var id = $F(select).match(/(\d+)\)$/).last();
    
    var template = "<div class='v-email' id='vendor_mail_" + id + "'><div class='left clear' style='text-align: right; font-size: 85%;'>" + name + "</div><div class='right'><input type='text' name='emails[" + id + "]' class='text vendor-email' value='" + email + "' style='width: 60%;' /> <a href='#' style='font-size: 85%;' onclick='$(this).up(\"div\").up(\"div\").replace(); return false;'>delete</a></div></div>";
    
	if(!$('vendor_mail_' + id)) {
	    new Insertion.Bottom('vendor_emails', template);
	}
    $(select).focus();
    
		//     try {
		// var count = $$('#select option').length;
		//         var selectedIndex = select.selectedIndex;
		//         $(select).options[selectedIndex].remove();
		//         $(select).selectedIndex = (selectedIndex + 1) % count;
		//     } catch(error) {}
}

function addVendorGroup(){	
	var currentVendorGroup = jQuery('#uxVendorGroupDropDown').val();
	var vendersForGroup = vendorsOfVendorGroups[currentVendorGroup];	
	jQuery(vendersForGroup).each(function(){
		jQuery('#select').val(this.toString());
		addVendor();
	});
	jQuery('#uxVendorGroupDropDown').focus();
}

function validateAllEmails(){
    var invalids = [];
    var emails = [];
    jQuery('.vendor-email').each(function(elem){
    	 emailarray = [];
    	 singleEmails = elem.value.gsub(/;| +/, ',').gsub(/,+/, ',').split(",");
    	 singleEmails.each(function(elem){ emailarray.push(elem); }); 
    	}) 
    jQuery('.vendor-email').each(function(elem){
        if(!Telaeris.isValidEmail($F(elem))) {
            invalids.push($F(elem));
        }
    });
    if(invalids.length == 0) return true;
    else {
        alert('Invalid or blank email(s) -> ' + invalids.join(', '));
        return false;
    }
        
}

jQuery('#mail').submit(function(){
	var invalidEmails = [];
	if(jQuery('.vendor-email').length == 0){
		alert("Please add one or more vendors to the list");
		return false;
	}

	jQuery('.vendor-email').each(function(index, elem){ 		
 	   	//take out spaces and semicolons, replcae with commas, replace multiple commas with a single comma
 	   		//var item = jQuery('.vendor-email')[index];
    		var emails = elem.value.gsub(/;| +/, ',').gsub(/,+/, ',').split(",");  
    		var invalids = [];
    		var valids = [];
    
    		emails.each(function(email){
    	    
    	    	if(Telaeris.isValidEmail(email)) {
    	        	valids.push(email);
    	    	}
    	    	else {
    	        	invalids.push(email);
    	    	}
    		});
    
    		if(invalids.length > 0) {
    	    	invalids.each(function(email){
    	        	invalidEmails.push(email);
    	    	});
    	    	elem.ClassName += " error";
    		}
    		else {
	    	    elem.value = valids.join(", " );
	    	    
	    	    elem.className = elem.className.gsub('error','');
    		}
	});
	
	if(invalidEmails.length > 0) {
		var alertMessage = '';
    	    invalidEmails.each(function(email){
    	        alertMessage += "* '" + email + "' is an invalid email address\n";
    	    });
    	alert(alertMessage);
    	return false;
	}
	else {
		return true;
	}
	
})


$('vendor_filter').observe('focus', function(event){
   var filter = Event.element(event);
   if($F(filter) == 'Search Vendors') {
       filter.value = '';
       filter.setStyle({color: '#000', fontStyle: 'normal'});
   }
});

$('vendor_filter').observe('blur', function(event){
    var filter = Event.element(event);
    if($F(filter).match(/^\s*$/)){
        filter.value = 'Search Vendors';
        filter.setStyle({color: '#888', fontStyle: 'italic'});
    }
});

$('vendor_filter').observe('keydown', function(event){
    if(event.keyCode == 13) {
        Event.stop(event);
        setTimeout(function(){
            var query = $F(Event.element(event));
            new Ajax.Request('/material_requests/filter_vendors/search/', {method: 'get', parameters: 'query=' + query.escapeHTML()});
        }, 300);
    }
});

$('vendor_filter_submit').observe('click', function(event){
    Event.stop(event);
    var query = $F('vendor_filter');
    if(query == "Search Vendors") { return; }
    new Ajax.Request('/material_requests/filter_vendors/search/', {method: 'get', parameters: 'query=' + query.escapeHTML()});
});

$('vendor_filter_reset').observe('click', function(event){
    Event.stop(event); 
    new Ajax.Request('/material_requests/filter_vendors/search/', {method: 'get', parameters: 'query='});
    $('vendor_filter').value = '';
});
</script>

app/views/material_requests/mail_to_purchaser.html.erb
<script type="text/javascript" charset="utf-8">
    function checkEmailTo(){
        if($F('email').match(/^\s*$/)) {
            alert("Please enter an email address.");
            return false;
        }
        else {
            return Telaeris.validateEmails('email');
        }
    }

    function sendQuoteToVendor(){
        var url = "/material_requests/email_quote/<%= @material_request.id.to_s %>?message=";
        var message = $F('message').escapeHTML();

        window.location = url + message;
    }
</script>

<form id="mail" action="/material_requests/deliver_mail_to_purchaser/<%= @material_request.id %>" method="post" class="edit" onsubmit="return checkEmailTo();">
  <!-- <p>
    <label>Email To:&nbsp;&nbsp;&nbsp;<%= link_to "Purchaser", "#", :onclick => "$('vendor_name','search_for_vendor').invoke('hide');$('email').value='#{@email}';$('autoprint').show();" %>&nbsp;&nbsp;/&nbsp;&nbsp;<%= link_to "Vendor", "#", :onclick => "$('vendor_name','search_for_vendor').invoke('show');$('email').value='#{@vendor_email}';$('vendor_name').value='#{@vendor_name}';$('autoprint').hide();" %>&nbsp;&nbsp;&nbsp;<img src='/images/load.gif' id="loading" style="display: none" /></label>

    <label id="search_for_vendor" style="display:none;">  <br />Search for Vendor:</label>
    <%= text_field_with_auto_complete :vendor, :name, :value => "#{@vendor_name}", :style => "display:none;", :onblur => remote_function(:url => vendor_email_material_request_path, :with => "Form.serialize('mail')", :method => :get, :before => "$('loading').show()", :complete => "$('loading').hide();")  %>
  </p> -->


<% if(current_employee.purchasing? || current_employee.admin?) %>
  <p>
      <a href="#quote" onclick="sendQuoteToVendor()">Send Quote to Vendor</a>
  </p>
<% end %>

  <p>
    <label>Email To: &nbsp;&nbsp;<a href="#" onclick="return Telaeris.changeEmail('email', '');">Clear</a> /


                                <a href="#" onclick="return Telaeris.changeEmail('email', '<%="#{ENV['WAREHOUSE_EMAIL']}" %>');"><%="#{ENV['WAREHOUSE_NAME']}" %></a>
                                <% if !current_employee.email.blank? %>
                                  / <a href="#" onclick="return Telaeris.changeEmail('email', '<%= current_employee.email %>');"><%= current_employee.short_name %></a>
                                <% end %>
                                <% if @material_request.requester && !@material_request.requester.email.blank? && @material_request.requester != current_employee %>
                                  / <a href="#" onclick="return Telaeris.changeEmail('email', '<%= @material_request.requester.email %>');"><%= @material_request.requester.short_name %></a>
                                <% end %>
                                / <%= select_tag "buyer_emails", options_for_select(Employee.buyer_list_of_emails_for_select_tag, "Buyer"), :style => 'display: inline; width: 130px;', :onchange => "Telaeris.changeEmail('email', $('buyer_emails').value); $('buyer_emails').value = 'Buyer'; return;" %>
                                </label>
    <textarea id="email" name="email" type="text"><%= @email %></textarea>
    <span class="description">Separate email addresses by commas, semi-colons, or spaces</span>
  </p>
  <p>
    <label>Message:</label>
    <textarea name="message" id="message" style="width: 400px; height: 100px;"></textarea>
  </p>
  <input type="submit" value="Email Request" /> or <%= link_to "Cancel & Go Back", edit_material_request_path(@material_request) %>
</form>

app/views/material_requests/new_quote.html.erb
<% if !@material_request.authorized? && !@material_request.partially_authorized? %>
	<div style="text-align: center; font-size: 110%; color: red; background-color: #fcc; border: 1px solid #f66; border-right: 2px solid #f77; border-bottom: 2px solid #f77; width: 70%; padding: 7px; margin-bottom: 12px;">
		This material request has not been <b>authorized</b> yet, are you sure you want to send out a quote?
		<span style="font-size: 80%;">
		<%= link_to "Back to Material Request", edit_material_request_path(@material_request) %>
		</span>
	</div>
<% end %>


<form method="post" class="edit full" style="width: 50%;" id="new_quote">
	<input type="hidden" value="<%= @material_request.id %>" />
	
	<p>
		<label>Which vendor is this quote from?</label>
	    <%= text_field_with_auto_complete :vendor, :name, :class => "text", :value => (@material_request.suggested_vendor || "") %>
		<% if flash[:error] %>
			<span class="error" style="font-weight: bold; color: red;"><%= flash[:error] %></span>
		<% end %>

		
    </p>
    <%= render :partial => "request_attachments_for_quote", :locals => { :material_request => @material_request} %>
	<p>
		<input type="submit" value="Create Quote">
	</p>
</form>