config/routes.rb
MaterialTracker::Application.routes.draw do

  resources :vendor_questionnaire_groups
  resources :questionnaire_groups
  resources :questionairre_items
  post '/save_questionairre_answers' => 'questionairre_items#save_answer'
  post '/delete_answer' => 'questionairre_items#delete_answer'

  resources :groups
  match '*path' => 'application#options_for_mopd', :via => :options
  match '/popv_viewer' => 'sessions#login_as_popv_viewer'
  match '/inventory_items/tags' => 'inventory_items#tags'
  match '/inventory_items/edit_basket' => 'inventory_items#edit_basket'
  resources :general_references do
    collection do
      get :search
    end
    member do
      get :download
    end

  end
  
  resources :questions do
    collection do
      get :search
    end
    resources :question_answers
  end
  
  resources :questionnaires do
    collection do
      get :search
    end
  end

  resources :events
  resources :emails
  resources :cart_items
  resources :carts do
    collection do
      get :search
      get :recent_search
      put :issue
      get :get_order
      get :recent
    end

  end

  match '/get_order' => 'carts#get_order'
  resources :bills do

    member do
      post :approve
      post :review
      post :disapprove
      post :unreview
      get :request_for_quote_pdf
    end

  end

  resources :bill_items do
    collection do
      post :create_many
    end


  end

  match '/sext/save_tabs' => 'sext#save_tabs'
  match '/sext/tabs' => 'sext#tabs'
  match '/sext/:resource/' => 'sext#index', :via => :get
  match '/sext/:resource/store' => 'sext#store', :via => :get
  match '/sext/:resource/:id' => 'sext#show', :via => :get
  match '/sext/:resource/' => 'sext#create', :via => :post
  match '/sext/:resource/:id' => 'sext#update', :via => :put
  match '/sext/:resource/:id' => 'sext#destroy', :via => :delete
  match '/piping/clone_class/:id' => 'piping#clone_class'
  match '/piping/compare_piping_classes/:ids' => 'piping#compare_piping_classes', :format => 'json'
  match '/piping/compare_piping_classes.csv/:ids' => 'piping#compare_piping_classes', :format => 'csv'
  match '/orders/select_pos' => 'orders#select_pos'
  match '/piping_class_details/prepend_text_to_descriptions' => 'piping_class_details#prepend_text_to_descriptions', :via => :put
  match '/' => 'home#index'
  match '/menu' => 'home#menu', :as => :main_menu
  match '/superuser' => 'home#superuser'
  match '/changelog' => 'home#changelog'
  match '/warehouse' => 'orders#warehouse'
  match '/orders/add_line_item' => 'orders#add_line_item'
  match '/remote_client/:action' => 'remote_client#index'
  match '/remote_client/:action/:id' => 'remote_client#index'
  match '/material_requests/bill' => 'material_requests#bill', :as => :bill
  match '/material_requests/sample_csv' => 'material_requests#sample_csv', :as => :bill
  resources :record_changelogs do
    collection do
      post :update_comment
    end
    member do
      get :get_attachment
    end

  end

  resources :sessions
  resources :inventory_items do
    collection do
      get :search
    end


  end

  resources :companies do
    collection do
      get :search
    end


  end

  resources :units do
    collection do
      get :search
    end


  end

  resources :quotes do
    collection do
      get :search
    end


  end

  resources :bulk_changes do
    collection do
      post :tables
      post :fields
      post :search_results
      post :finalize_replace
    end


  end

  resources :boms do
    collection do
      get :search
      get :excel
    end


  end

  resources :piping do
    collection do
      get :search
      get :classes_service
      get :classes_only
      get :classes_only_incl_archived
      get :units_for_measure
      get :piping_sizes
      get :piping_class_details
      get :piping_components
      get :all_classes_pdf
      get :notes_pdf
    end
    member do
      get :details_pdf
      get :valves_pdf
      post :increase_order
      post :decrease_order
      post :increase_group_order
      post :decrease_group_order
    end

  end

  resources :piping_class_details do
    collection do
      get :search
    end
    member do
      put :add_note
    end

  end

  resources :piping_components do
    collection do
      get :search
      get :associated_piping_classes
    end


  end

  resources :piping_subcomponents do
    collection do
      get :search
    end


  end

  resources :piping_specifications do
    collection do
      get :search
    end


  end

  resources :piping_descriptions do
    collection do
      get :search
    end


  end

  resources :user_notes do
    collection do
      get :search
    end


  end

  resources :valve_components do
    collection do
      get :search
    end


  end

  resources :manufacturers do
    collection do
      get :search
    end


  end

  resources :piping_notes do
    collection do
      get :search
    end


  end

  match '/valves/clone/:id' => 'valves#clone'
  resources :valves do
    collection do
      get :search
      get :all_pdf
      get :comparison_pdf
      get :related_valve_components
      get :related_manufacturers
      get :related_old_manufacturers
      get :related_piping_classes
      get :related_piping_references
      get :valve_components
      get :pdf
      post :supersede_manufacturer
      post :undo_supersede_manufacturer
      post :add_manufacturer
      put :edit_manufacturer
      delete :delete_manufacturer
    end
    member do
      put :archive
    end

  end

  resources :popv do
    collection do
      get :search
      post :upload_reference_documents
      get :popv_user_guide
    end


  end

  resources :employees do
    collection do
      get :search
    end


  end

  resources :orders do
    collection do
      get :test
      get :search
      get :complete_vendor
    end
    member do
      get :complete_employee
    end

  end

  resources :reminders do
    collection do
      get :search
    end


  end

  resources :reference_number_types
  resources :vendors do
    collection do
      get :search
    end


  end

  resources :po_statuses do
    collection do
      get :search
    end


  end

  resources :vendor_groups do
    collection do
      get :search
    end


  end

  resources :material_requests do
    collection do
      get :search
    end
    member do
      get :update_items_from_request
      get :pdf
      get :acknowledge
      get :vendor_email
      get :new_from_bom
      get :duplicate
      get :duplicate_with_items
      get :get_purchaser_group
    end

  end

  resources :requested_line_items
  resources :piping_references
  resources :piping_reference_attachings do
    collection do
      post :create_with_piping_reference
    end


  end

  resources :tickets do
    collection do
      get :search
    end


  end

  resources :links
  match '/init-questionnaire/(:id)' => 'questionnaire_workflows#init_questionnaire', :as => :init_questionnaire_workflow
  match 'vendor-questionnaire/(:id)' => "questionnaire_workflows#show", :as => :show_question
  
  get 'vendor-answer-questionnaire/(:id)' => 'questionnaire_workflows#vendor_view', :as => :vendor_view
  post 'vendor-answer-questionnaire/(:id)' => 'questionnaire_workflows#vendor_answer', :as => :vendor_answer
  get 'approval/(:id)' => 'questionnaire_workflows#approval_view', :as => :approval_view
  post 'approval/(:id)' => 'questionnaire_workflows#approval', :as => :approval
  match 'completed-vendor-questionnaire/(:id)' => 'questionnaire_workflows#completed' , :as => :complete_vendor_questionnaire
  match 'application_approved/(:id)' => 'questionnaire_workflows#application_approved' , :as => :application_approved
  match '/signup' => 'employees#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/reports' => 'reports#index', :as => :reports
  match '/reports/email' => 'reports#email'
  match '/csv' => 'reports#csv', :as => :csv
  match '/contact_us' => 'home#contact_us', :as => :contact_us
  match '/docs' => 'application#docs'
  match '/admin/new_message' => 'admin/messages#new_admin_message'
  match '/admin/index_sphinx' => 'admin/utilities#index_sphinx'
  match '/:controller(/:action(/:id))'
  match ':controller/:action' => '#index'
  match ':controller' => '#index'

end

app/controllers/home_controller.rb
# The home controller is for all static pages
#   * index.rhtml - login screen
#   * help-orders.rhtml - help window for orders
class HomeController < ApplicationController
  caches_page "help-orders"
  skip_before_filter :login_required, :except => [:superuser, :reset_messages, :menu]
  before_filter :superuser_required, :only => [:superuser, :reset_messages]
  SUPERUSERS = %w(carta cstotts telaeris_admin)
  UPDATEMESSAGE = "New! - View the <a href='/changelog'>CHANGELOG</a> to see recent changes to the application"

  def index
    flash[:error] ||= nil

    if logged_in?
      if current_employee.menu?
        redirect_to(:controller => "home", :action => "menu")
      elsif current_employee.orders?
        redirect_to(:controller => "orders", :action => "index")
      elsif current_employee.material_requests?
        if current_employee.purchasing? || current_employee.admin?
          redirect_to(:controller => "material_requests", :action => "index")
        else
          redirect_to(:controller => "material_requests", :action => "index")
        end
      elsif current_employee.web_requests?
        redirect_to(:controller => "carts", :action => "recent")
      elsif current_employee.reports?
        redirect_to(:controller => "reports", :action => "index")
      elsif current_employee.popv?
        redirect_to(:controller => "popv", :action => "index")
      else
        redirect_to(:controller => "home", :action => "menu")
      end
    end
  end

  def changelog
    #raise Rails.root.inspect
    text = IO.read(Rails.root + 'CHANGELOG').html_safe
    @log = text #BlueCloth::new(text).to_html
  end

  def reset_messages
    if request.post?
      Employee.update_all(:seen_updates => false)
      flash[:notice] = "All employees will now see an update message when they first login"
      redirect_to :action => "superuser"
    end
  end

  def menu
    render :action => "menu", :layout => "application"
  end

  def contact_us
  	@user_name = logged_in? ? current_employee.entire_full_name : ''
  	@user_email = logged_in? ? current_employee.email : ''
  end

  # generic email action
  # params[:from], params[:to], params[:subject], params[:body], params[:redirect_to]
  def email
    options = { :from => params[:email], :to => "support@telaeris.com", :subject => params[:subject], :body => "From: #{params[:user]} <#{params[:email]}>\r\nCategory: #{params[:category]}\r\nSubject:#{params[:subject]}\r\n\r\n#{params[:body]}"}
    RequestMailer.deliver_generic(options)
    flash[:notice] = "Your email was sent successfully"
    redirect_to params[:redirect]
  end

  def superuser
    if request.post?
      employee = Employee.find_by_login(params[:login])
      if employee
        self.current_employee = employee
        flash[:notice] = "Logged in as #{params[:login]}"
        redirect_to :action => "index"
      else
        flash[:notice] = "Could not find a user with login #{params[:login]}"
        redirect_to :controller => "home", :action => "superuser"
      end
    end
  end # end superuser

  private
  def superuser_required
    if !SUPERUSERS.include?(current_employee.login)
      flash[:error] = "You do not have super-user priveleges, please contact an administrator"
      redirect_to :action => :index and return
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def alternating_row
		res = ""
		if(@row_count%2 > 0)
			res = "odd"
		else
			res = "even"
		end

		@row_count += 1
		return res
	end
end

app/views/home/changelog.html.erb
<div id="changelog">
    <%= @log %>    
</div>

app/views/home/contact_us.html.erb
<div style="width: 600px">
	<% if params[:sent] %>
	<h2 style="color: green; font-weight: bold;">Your message has been sent to us and we will reply to you shortly via email</h2>
	<% else %>
	<h2 style="font-weight: bold;">Contact us for feedback, suggestions, or troubleshooting:</h2>
	<% end %>
	<form action="/home/email" method="POST" class="edit">
		<input type="hidden" name="auth_token" value="8abc68357d9f862a5e2d834c8d8d4aa244620661" />
		<input type="hidden" name="redirect" value="/contact_us?sent=true" />
		<input type="hidden" name="user" value="<%= @user_name %>" />
		<p>
			<label>Email</label>
			<input type="text" name="email" value="<%= @user_email %>" class="text" />
		</p>
		<p>
			<label>Subject</label>
			<input type="text" name="subject" value="" class="text" />
		</p>
		<p>
			<label>Description</label>
			<textarea name="body" style="width: 400px; height: 140px;"></textarea>
		</p>
		<p>
			<label>Category</label>
			<select name="category">
				<option>Troubleshooting</option>
				<option>General Question</option>
				<option>Bug Report</option>
				<option>Feature Request</option>
			</select>
		</p>
		
		<p>
			<input type="submit" value="Send Message" />
		</p>
	</form>
</div>

app/views/home/index.html.erb
<style type="text/css" media="screen">
    body {
        background: #555;
    }

        /*  #company-branding {
            display: none;
          }

          #telaeris-branding {
            display: none;
          }
        */
    #content {
        text-align: center;
    }

    #login-area {
        width: 350px;
        margin: 0 auto;
    }

    #login-form {
        background-color: #ddd;
        border: 2px solid #111;
        border-bottom: 4px solid #111;
        padding: 15px;
        text-align: left;
        width: 100%;
    }

        /*  #login-bp-logo {
            position: relative;
            right: 40px;
            bottom: 20px;
          }

          #login-telaeris-logo {
            margin-top: 20px;
          }
        */

    #login-button {
        width: 150px;
        height: 30px;
        margin-top: 20px;
        font-size: 120%;
    }

/******************************
        New Login CSS
******************************/
    #signin-screen {
        color: #FFF;
        border: 3px solid #CCC;
        background-color: #777;
        padding: 20px;
        padding-top: 10px;
        margin-left: auto;
        margin-right: auto;
        width: 400px;
    }

    #signin-screen hr {
        height: 2px;
        background-color: #FFF;
        border: 0;
        margin-top: 10px;
    }

    #signin-screen h2 {
        font-size: 200%;
        text-align: center;
        color: #FFF;
        font-weight: bold;
        margin-bottom: 0;
    }

    #signin-screen fieldset {
        border: none;
        text-align: right;
        /*	margin-bottom: 0;*/
        padding: 0;

    }

    #signin-screen label {
        font-size: 2em;
        margin-left: 10px;
        line-height: 2em;
    }

    #signin-screen input {
        font-size: 150%;
    }

    #signin-screen input {
        margin-left: 10px;
        padding: 4px;
        width: 180px;
    }

    #signin-screen .button {
        font-size: 1.5em;
        text-align: center;
        margin-top: 10px;
        width: 188px;
    }

    #signin-screen a {
        display: inline;
        width: 200px;
        height: 40px;
        color: #0F0;
        font-size: 1.3em;
        font-weight: bold;
        text-decoration: none;
    }

    #signin-screen a:hover {
        text-decoration: underline;
        background-color: transparent;
    }

    #signin-screen span {
        font-size: 1.5em;
        margin-right: 20px;
        position: relative;
        bottom: 10px;
    }

    #signin-screen .login-warning {
        font-size: 120%;
        margin-top: 10px;
    }

    div.info-view-popv {
        text-align: center;
    }

</style>

<% if DEPLOY_SITE_NAME == /Carson/ -%>
    <div id="login-area">

      <!-- <img src="/graphics/bp.gif" id="login-bp-logo" /> -->
      <%= form_tag sessions_path, :class => "edit", :id => "login-form" do %>
          <p>
            <label>Username:</label>
            <%= text_field_tag :login, nil, :id => "login", :style => "width: 330px;", :value => params[:login] %>
          </p>

          <p>
            <label>Password:</label>
            <%= password_field_tag :password, nil, :style => "width: 330px;" %>
          </p>

          <p>
            <label class="inline">Remember Me</label>
            <%= check_box_tag :remember_me, 1, false, :style => "margin-right: 5px;" %>
          </p>

          <p class="description" style="color: #000;">
            Be sure to logout if this computer will be used by others
            <br/>
            <br/>
            <a href='/popv_viewer' style="color: green; text-decoration: underline;">Click here to view WebPOPV</a>
          </p>

          <p style="margin-bottom: 2px;">
            <%= submit_tag "Log In", :id => "login-button" %>
          </p>
      <% end %>

      <!-- <img src="/images/telaeris_logo.gif" id="login-telaeris-logo" /> -->
    </div>
<% else -%>

    <div id="signin-screen">
      <form action="/sessions" method="post">
        <% if resource_enabled?(:popv) %>

            <div class="info-view-popv">
              <a style="color: green; text-decoration: underline; text-align: center;" href="/popv_viewer">
                <img src="assets/login/view_popv_button.gif" alt="View Only"/>
              </a>
            </div>

            <hr>
        <% end %>

        <h2>Have an account?</h2>
        <fieldset>
          <label>Username:</label> <input type="text" name="login" class="focus"/>
          <br/>
          <label>Password:</label> <input type="password" name="password"/>
          <br/>
          <%= check_box_tag :remember_me, 1, false, :style => "margin-right: 5px;" %>
          <label style="font-size: 120%;">Remember Me</label>
          <br/>


          <input type="submit" value="Sign In" class="button"/>
        </fieldset>

        <hr>
        <p class="login-warning">
          Be sure to logout if this computer will be used by others
        </p>

      </form>
    </div>

<% end -%>

app/views/home/menu.html.erb
<style type="text/css" media="screen">
    td.resource, th.resource { width: 170px;}
    td.search, th.search { width: 200px;}
    td.action, td.search { font-size: 75%; }
</style>
<% @row_count = 0 %>
<table class="information" style="font-size: 130%;">
  <tr>
      <th class="resource">Main Menu</th>
      <th class="search">search</th>
      <th class="action">
          <% if !current_employee.warehouse?(true) && !receiving_view? %>
          actions
          <% end %>
      </th>
  </tr>
  <% if resource_enabled?(:material_requests) && !warehouse_view? && !receiving_view? %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Requests", material_requests_path(default_request_params) %></td>
      <td class="search">
        <%= render :partial => "/material_requests/search" %>
      </td>
      <td class="action">
        <%= link_to "create request", new_material_request_path %>
      </td>
  </tr>
  <% end %>

  <% if resource_enabled?(:carts) %>
	  <tr class="<%= alternating_row %>">
	      <td><%= link_to "Web Requests", recent_carts_path(default_request_params) %></td>
	      <td class="search">
	        <%= render :partial => "/carts/search" %>
	      </td>
	      <td class="action">
	          <% if !warehouse_view? && !receiving_view? %>
	            <%= link_to "create web request", carts_path %>
	          <% end %>
	      </td>
	  </tr>
  <% end %>

  <% if resource_enabled?(:orders) %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Orders", orders_path %></td>
      <td class="search">
        <%= render :partial => "/orders/search" %>
      </td>
      <td class="action">
         <% if current_employee.admin? || current_employee.purchasing? || current_employee.planning? %>
            <%= link_to "create order", new_order_path %>
         <% end %>
      </td>
  </tr>
  <% end %>


  <% if resource_enabled?(:inventory_items) %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Inventory", inventory_items_path %></td>
      <td class="search">
        <%= render :partial => "/inventory_items/search" %>
      </td>
      <td class="action">
        <%= link_to "create inventory item", new_inventory_item_path %>
      </td>
  </tr>
  <% end %>


  <% if resource_enabled?(:general_references) %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Files/References", general_references_path %></td>
      <td class="search">
        <%= render :partial => "/general_references/search" %>
      </td>
      <td class="action">
          <% if current_employee.admin? || current_employee.purchasing? %>
            <%= link_to "upload file", new_general_reference_path %>
          <% end %>
      </td>
  </tr>
  <% end %>

  <tr class="<%= alternating_row %>">
      <td><%= link_to "Units", units_path %></td>
      <td class="search">
        <%= render :partial => "/units/search" %>
      </td>
      <td class="action">
          <% if !warehouse_view? && !requesting_view? && !receiving_view? %>
            <%= link_to "create unit", new_unit_path %>
          <% end %>
      </td>
  </tr>
  <% if current_employee.need_details? %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Vendors", vendors_path %></td>
      <td class="search">
        <%= render :partial => "/vendors/search" %>
      </td>
      <td class="action"><%= link_to "create vendor", new_vendor_path %></td>
  </tr>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Vendor Groups", vendor_groups_path %></td>
      <td class="search">
        <%= render :partial => "/vendor_groups/search" %>
      </td>
      <td class="action"><%= link_to "create vendor group", new_vendor_group_path %></td>
  </tr>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Companies", companies_path %></td>
      <td class="search">
        <%= render :partial => "/companies/search" %>
      </td>
      <td class="action"><%= link_to "create company", new_company_path %></td>
  </tr>
  <% end %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Users", employees_path %></td>
      <td class="search">
          <%= render :partial => "/employees/search" %>
      </td>
      <td class="action">
          <% if !current_employee.warehouse?(true) && !requesting_view? && !receiving_view? && !current_employee.engineer? %>
              <%= link_to "create user", new_employee_path %>
          <% end %>
      </td>
  </tr>

  <% if resource_enabled?(:quotes) %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Quotes", quotes_path %></td>
      <td class="search">
          <%= render :partial => "/quotes/search" %>
      </td>
      <td class="action">
          
      </td>
  </tr>
  <% end %>

  <% if resource_enabled?(:reports) %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Reports", reports_path %></td>
      <td class="action"></td>
      <td></td>
  </tr>
  <% end %>

  <% if resource_enabled?(:events) %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "Events", events_path %></td>
      <td class="action"></td>
      <td></td>
  </tr>
  <% end %>

  <% if resource_enabled?(:live) %>
  <tr class="<%= alternating_row %>">
  	   <td><%= link_to "Live Info", url_for(:controller => "live") %></td>
	   <td class="action"></td>
		<td></td>
  </tr>
  <% end %>

  <% if current_employee.admin? %>
    <tr class="<%= alternating_row %>">
         <td><%= link_to "Import/Export", url_for(:controller => "reports", :action =>"import_export") %></td>
       <td class="action"></td>
       <td></td>
    </tr>
  <% end %>
  
  <tr class="<%= alternating_row %>">
  	   <td><%= link_to "Tickets", url_for(:controller => "tickets") %></td>
	   <td class="action"></td>
		<td></td>
  </tr>

  <% if resource_enabled?(:popv) %>
  <tr class="<%= alternating_row %>">
      <td><%= link_to "POPV", url_for(:controller => "popv") %></td>
      <td class="search">

      </td>
      <td class="action"></td>
  </tr>
  <% end %>
  <% if current_employee.admin? %>
    
	  <% if resource_enabled?(:groups) %>
	  <tr class="<%= alternating_row %>">
	  	   <td><%= link_to "Groups", url_for(:controller => "groups") %></td>
		   <td class="action"></td>
		   <td></td>
	  </tr>
	  <% end %>

	  <% if resource_enabled?(:reference_numbers) %>
	  <tr class="<%= alternating_row %>">
	  	   <td><%= link_to "Reference Numbers", url_for(:controller => "reference_number_types") %></td>
		   <td class="action"></td>
		   <td></td>
	  </tr>
	  <% end %>



    <tr class="<%= alternating_row %>">
         <td><%= link_to "PO Statuses", url_for(:controller => "po_statuses") %></td>
       <td class="action"></td>
       <td></td>
    </tr>




    
  <% end %>
</table>

app/views/home/superuser.html.erb
<style type="text/css" media="screen">
  body {
    background: #555;
  }
  
/*  #company-branding {
    display: none;
  }
  
  #telaeris-branding {
    display: none;
  }
*/  
  #content {
    text-align: center;
  }
  
  #login-area {
    width: 350px;
    margin: 0 auto;
  }

  #login-form {
    background-color: #ddd; 
    border: 2px solid #111; 
    border-bottom: 4px solid #111;
    padding: 15px; 
    text-align: left;
    width: 100%;
  }
  
/*  #login-bp-logo {
    position: relative;
    right: 40px;
    bottom: 20px;
  }
  
  #login-telaeris-logo {
    margin-top: 20px;
  }
*/</style>


<div id="login-area">
  
  <!-- <img src="/graphics/bp.gif" id="login-bp-logo" /> -->
  
  
  <div id="login-form">
  <%= form_tag "/superuser", :class => "edit" do %>
  <p>
    <label>Username:</label>
    <%= text_field_tag :login, nil, :id => "login", :style => "width: 330px;" %>
  </p>
  <p class="menu" style="margin-bottom: 2px;">
    <%= submit_tag "Login as this User" %>
  </p>
  <% end %>
  
  <hr />
  
  <%= button_to "Reset Employee Messages", "/home/reset_messages", :method => :post %>
  </div>
  
  <!-- <img src="/images/telaeris_logo.gif" id="login-telaeris-logo" /> -->
  
</div>