config/routes.rb
MaterialTracker::Application.routes.draw do

  resources :vendor_questionnaire_groups
  resources :questionnaire_groups
  resources :questionairre_items
  post '/save_questionairre_answers' => 'questionairre_items#save_answer'
  post '/delete_answer' => 'questionairre_items#delete_answer'

  resources :groups
  match '*path' => 'application#options_for_mopd', :via => :options
  match '/popv_viewer' => 'sessions#login_as_popv_viewer'
  match '/inventory_items/tags' => 'inventory_items#tags'
  match '/inventory_items/edit_basket' => 'inventory_items#edit_basket'
  resources :general_references do
    collection do
      get :search
    end
    member do
      get :download
    end

  end
  
  resources :questions do
    collection do
      get :search
    end
    resources :question_answers
  end
  
  resources :questionnaires do
    collection do
      get :search
    end
  end

  resources :events
  resources :emails
  resources :cart_items
  resources :carts do
    collection do
      get :search
      get :recent_search
      put :issue
      get :get_order
      get :recent
    end

  end

  match '/get_order' => 'carts#get_order'
  resources :bills do

    member do
      post :approve
      post :review
      post :disapprove
      post :unreview
      get :request_for_quote_pdf
    end

  end

  resources :bill_items do
    collection do
      post :create_many
    end


  end

  match '/sext/save_tabs' => 'sext#save_tabs'
  match '/sext/tabs' => 'sext#tabs'
  match '/sext/:resource/' => 'sext#index', :via => :get
  match '/sext/:resource/store' => 'sext#store', :via => :get
  match '/sext/:resource/:id' => 'sext#show', :via => :get
  match '/sext/:resource/' => 'sext#create', :via => :post
  match '/sext/:resource/:id' => 'sext#update', :via => :put
  match '/sext/:resource/:id' => 'sext#destroy', :via => :delete
  match '/piping/clone_class/:id' => 'piping#clone_class'
  match '/piping/compare_piping_classes/:ids' => 'piping#compare_piping_classes', :format => 'json'
  match '/piping/compare_piping_classes.csv/:ids' => 'piping#compare_piping_classes', :format => 'csv'
  match '/orders/select_pos' => 'orders#select_pos'
  match '/piping_class_details/prepend_text_to_descriptions' => 'piping_class_details#prepend_text_to_descriptions', :via => :put
  match '/' => 'home#index'
  match '/menu' => 'home#menu', :as => :main_menu
  match '/superuser' => 'home#superuser'
  match '/changelog' => 'home#changelog'
  match '/warehouse' => 'orders#warehouse'
  match '/orders/add_line_item' => 'orders#add_line_item'
  match '/remote_client/:action' => 'remote_client#index'
  match '/remote_client/:action/:id' => 'remote_client#index'
  match '/material_requests/bill' => 'material_requests#bill', :as => :bill
  match '/material_requests/sample_csv' => 'material_requests#sample_csv', :as => :bill
  resources :record_changelogs do
    collection do
      post :update_comment
    end
    member do
      get :get_attachment
    end

  end

  resources :sessions
  resources :inventory_items do
    collection do
      get :search
    end


  end

  resources :companies do
    collection do
      get :search
    end


  end

  resources :units do
    collection do
      get :search
    end


  end

  resources :quotes do
    collection do
      get :search
    end


  end

  resources :bulk_changes do
    collection do
      post :tables
      post :fields
      post :search_results
      post :finalize_replace
    end


  end

  resources :boms do
    collection do
      get :search
      get :excel
    end


  end

  resources :piping do
    collection do
      get :search
      get :classes_service
      get :classes_only
      get :classes_only_incl_archived
      get :units_for_measure
      get :piping_sizes
      get :piping_class_details
      get :piping_components
      get :all_classes_pdf
      get :notes_pdf
    end
    member do
      get :details_pdf
      get :valves_pdf
      post :increase_order
      post :decrease_order
      post :increase_group_order
      post :decrease_group_order
    end

  end

  resources :piping_class_details do
    collection do
      get :search
    end
    member do
      put :add_note
    end

  end

  resources :piping_components do
    collection do
      get :search
      get :associated_piping_classes
    end


  end

  resources :piping_subcomponents do
    collection do
      get :search
    end


  end

  resources :piping_specifications do
    collection do
      get :search
    end


  end

  resources :piping_descriptions do
    collection do
      get :search
    end


  end

  resources :user_notes do
    collection do
      get :search
    end


  end

  resources :valve_components do
    collection do
      get :search
    end


  end

  resources :manufacturers do
    collection do
      get :search
    end


  end

  resources :piping_notes do
    collection do
      get :search
    end


  end

  match '/valves/clone/:id' => 'valves#clone'
  resources :valves do
    collection do
      get :search
      get :all_pdf
      get :comparison_pdf
      get :related_valve_components
      get :related_manufacturers
      get :related_old_manufacturers
      get :related_piping_classes
      get :related_piping_references
      get :valve_components
      get :pdf
      post :supersede_manufacturer
      post :undo_supersede_manufacturer
      post :add_manufacturer
      put :edit_manufacturer
      delete :delete_manufacturer
    end
    member do
      put :archive
    end

  end

  resources :popv do
    collection do
      get :search
      post :upload_reference_documents
      get :popv_user_guide
    end


  end

  resources :employees do
    collection do
      get :search
    end


  end

  resources :orders do
    collection do
      get :test
      get :search
      get :complete_vendor
    end
    member do
      get :complete_employee
    end

  end

  resources :reminders do
    collection do
      get :search
    end


  end

  resources :reference_number_types
  resources :vendors do
    collection do
      get :search
    end


  end

  resources :po_statuses do
    collection do
      get :search
    end


  end

  resources :vendor_groups do
    collection do
      get :search
    end


  end

  resources :material_requests do
    collection do
      get :search
    end
    member do
      get :update_items_from_request
      get :pdf
      get :acknowledge
      get :vendor_email
      get :new_from_bom
      get :duplicate
      get :duplicate_with_items
      get :get_purchaser_group
    end

  end

  resources :requested_line_items
  resources :piping_references
  resources :piping_reference_attachings do
    collection do
      post :create_with_piping_reference
    end


  end

  resources :tickets do
    collection do
      get :search
    end


  end

  resources :links
  match '/init-questionnaire/(:id)' => 'questionnaire_workflows#init_questionnaire', :as => :init_questionnaire_workflow
  match 'vendor-questionnaire/(:id)' => "questionnaire_workflows#show", :as => :show_question
  
  get 'vendor-answer-questionnaire/(:id)' => 'questionnaire_workflows#vendor_view', :as => :vendor_view
  post 'vendor-answer-questionnaire/(:id)' => 'questionnaire_workflows#vendor_answer', :as => :vendor_answer
  get 'approval/(:id)' => 'questionnaire_workflows#approval_view', :as => :approval_view
  post 'approval/(:id)' => 'questionnaire_workflows#approval', :as => :approval
  match 'completed-vendor-questionnaire/(:id)' => 'questionnaire_workflows#completed' , :as => :complete_vendor_questionnaire
  match 'application_approved/(:id)' => 'questionnaire_workflows#application_approved' , :as => :application_approved
  match '/signup' => 'employees#new', :as => :signup
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/reports' => 'reports#index', :as => :reports
  match '/reports/email' => 'reports#email'
  match '/csv' => 'reports#csv', :as => :csv
  match '/contact_us' => 'home#contact_us', :as => :contact_us
  match '/docs' => 'application#docs'
  match '/admin/new_message' => 'admin/messages#new_admin_message'
  match '/admin/index_sphinx' => 'admin/utilities#index_sphinx'
  match '/:controller(/:action(/:id))'
  match ':controller/:action' => '#index'
  match ':controller' => '#index'

end

app/helpers/piping_helper.rb
module PipingHelper
end

app/views/piping/_actions.html.erb
<% if params[:action] != 'popv_notes'  %>
    <li><%= img_button "Show All POPV", "order_list.png", url_for({:controller => 'piping'}) %></li>
<% end %>
<% if params[:action] == 'piping_class_details'  %>
    <li><%= img_button_function "Add Piping Detail", "order_add.png",
	"Effect.SlideDown('new_piping_class_detail_#{params[:id]}');return false;new Effect.Highlight('new_piping_class_detail_#{params[:id]}');" %></li>
<% end %>

app/views/piping/_detail_component.html.erb
<div id="piping_class_detail_component_<%= "#{piping_class_detail.id}" %>">
<% unless piping_class_detail.piping_component.nil? %>

	<tr>
		<th>Piping Component</th>
		<th>Display Seq Number</th>
	</tr>
	<tr>
		<td><%= h piping_class_detail.piping_component.piping_component %></td>
		<td><%= h piping_class_detail.piping_component.display_seq_no %></td>
	</tr>
	<%= render :partial => 'detail_subcomponents', :locals => {:detail_subcomponents => piping_class_detail.piping_component.piping_subcomponents} %>
<% end %>
</div>

app/views/piping/_detail_notes.html.erb
<div id="piping_class_detail_notes_detail_<%="#{piping_class_detail.id}"%>">
<% unless piping_class_detail.piping_notes.nil? %>
<table class="noprint information clear">
  <% piping_class_detail.piping_notes.each do |note| %>
    <tr id="piping_class_detail_note_<%= "#{note.id}" %>">
      <td style="width: 80px;">NOTE</td>
      <td><%= h note.note_text %></td>
    </tr>
  <% end %>
</table>
<% end %>
</div>

app/views/piping/_detail_subcomponents.html.erb
<% if detail_subcomponents.size > 0 %>
	<tr><th colspan=2>PIPING SUBCOMPONENTS</th></tr>
	<% detail_subcomponents.each do |sub_c| %>
	<tr>
		<td>Description</td>
		<td><%= h sub_c.description %></td>
	</tr> 
	 <% end %>
<% end %>

app/views/piping/_detail_valve.html.erb
<div id="piping_class_detail_valve_<%= "#{piping_class_detail.id}" %>">
<% unless piping_class_detail.valve.nil? %>
<table class="noprint information clear">
	<tr>
		<th>Valve Code</th>
		<th>Description</th>
	</tr>
	<tr>
		<td><%= piping_class_detail.valve.valve_code %></td>
		<td>
		<% if piping_class_detail.valve.discontinued? %>
		<strong style="font-size: 110%; color: red;">DISCONTINUED</strong>
		<% end %>
		<%= piping_class_detail.valve.valve_note %> -- <%= piping_class_detail.valve.manufacturers_remarks %></td>
	</tr>
</table>
<% end %>
</div>

app/views/piping/_new_piping_class_detail.html.erb
<div id="new_piping_class_detail_<%="#{piping_class_id}"%>" style="display:none">
	<form method="post" class="edit full" style="width: 80%;" id="new_quote">
		<input />
		<input />
		<input />
		<input />
	</form>
</div>

app/views/piping/_notes_and_valve.html.erb
<table class="noprint information clear" id="notes_and_valve">
  <tr>
    <th>Notes/Valve</th>
    <th>#ID</th>
    <th>Description</th>
  </tr>
    
  <% if @bc9 || @bc10 || @bc11 %>
  <tr>
    <td colspan="2" style="width: 160px;">BC</td>
    <td>
      <% if @bc9 %> <a href="/images/bc9.jpg">BC-9</a> <% end %>
      <% if @bc10 %> <a href="/images/bc10.jpg">BC-10</a> <% end %>
      <% if @bc11 %> <a href="/images/bc11.jpg">BC-11</a> <% end %>
    </td>
  </tr>
  <% end %>
  
  <% if !@valve && @piping_notes.size == 0 %>
    <tr>
      <td colspan="3" style="text-align: center;">No Notes or Valves</td>
    </tr>
  <% end %>
  
  <% if @valve %>
    <tr>
      <td style="width: 80px;">VALVE</td>
      <td style="width: 80px;"><%= @valve.valve_code %></td>
      <td>
      <% if @valve.discontinued? %>
        <strong style="font-size: 110%; color: red;">DISCONTINUED</strong>
      <% end %>
      <%= @valve.valve_note %> -- <%= @valve.manufacturers_remarks %></td>
    </tr>
  <% end %>

  
  <% @piping_notes.each do |note| %>
    <tr>
      <td style="width: 80px;">NOTE</td>
      <td style="width: 80px;"><%= note.id %></td>
      <td><%= h note.note_text %></td>
    </tr>
  <% end %>
  
</table>

app/views/piping/_notes_cell.html.erb
<%= @piping_notes.map { |n| link_to_note(n) }.join(", ") %>

app/views/piping/_search.html.erb
<%= form_tag search_piping_path, :method => :get do -%>
    <input type="text" value="Search POPV" onfocus="InterfaceHelper.clear(this);" onblur="InterfaceHelper.reset(this);" style="font-style: italic; color: gray; width: 180px;" name="q" />
<% end -%>

app/views/piping/_valve_cell.html.erb
<% if @valve %>
<%= @valve.valve_code %> : <%= @valve.valve_note %>
<% end %>

app/views/piping/index.html.erb
<style type="text/css" media="screen">
    .img_sort a { padding: 2px; }
    .img_sort img { display: none; }
    .img_sort a img { display: inline; }
    th.class_code, td.class_code{ width: 90px;}
    th.desc, td.desc {}
    th.maintenance_note, td.maintenance_note { width: 120px; }
    th.service, td.service { width: 140px; }
</style>

<table class="information" cellspacing="0">
  <tr class="header">
    <th class="class_code">
      <%= link_to_sort "Piping Class", "piping_classes.class_code", :include => [:piping_classes] %>
    </th>
    <th class="maintenance_note">
      <%= link_to_sort "Maintenance Note", "piping_classes.maintenance_note" %>
    </th>
    <th class="service">
      <%= link_to_sort "Service", "piping_classes.service" %>
    </th>
  </tr>
</table>

<div id="maininfo">
  <table class="information" cellspacing="0">
    <% @piping_classes.each do |piping_class| %>
        <tr class="<%= cycle(:even, :odd) %>" id="piping_class_<%= "#{piping_class.id}" %>">
          <td class="class_code">
            <%= link_to piping_class.class_code, url_for({:action => 'piping_class_details', :id => piping_class.id}) %>
          </td>
          <td class="maintenance_note"><%= h piping_class.maintenance_note %></td>
          <td class="service"><%= h piping_class.service %></td>
        </tr>
    <% end %>
  </table>
</div>

<%= render 'shared/will_paginate', collection: @piping_classes %>
<%#= render :partial => "shared/paginate", :locals => { :collection => @piping_classes } %>

app/views/piping/piping_class_details.html.erb
<style type="text/css" media="screen">
    .img_sort a { padding: 2px; }
    .img_sort img { display: none; }
    .img_sort a img { display: inline; }
    th.description, td.description{ width: 400px;}
    th.component, td.component{ width: 150px;}
    th.valve, td.valve{ width: 150px;}
    th.notes, td.notes{ width: 300px;}
    th.bc, td.bc{}
</style>
<%= render :partial => 'new_piping_class_detail', :locals => {:piping_class_id => params[:id]} %>
<table class="noprint information clear">
<tr>
	<th class="description">Description</th>
	<th class="component">Component</th>
	<th class="valve">Valve</th>
	<th class="notes">Notes</th>
	<th class="bc">BC</th>
</tr>

<% @piping_class_details.each do |piping_class_detail| %>
<tr id="piping_class_detail_<%= "#{piping_class_detail.id}" %>" class="<%= cycle(:odd, :even) %>" >
	<td class="description">
		<%= h piping_class_detail.size_and_description %>
	</td>
	<td class="component">
		<% unless piping_class_detail.piping_component.nil? %>
			<%= h piping_class_detail.piping_component.piping_component %>
		<% end %>
	</td>
	<td class="valve">
		<% unless piping_class_detail.valve.nil? %>
			<%= h piping_class_detail.valve.valve_code %>
		<% end %>
	</td>
	<td class="notes">		
		<% if piping_class_detail.piping_notes.empty? %>
			<% @expand_style = "display:none" %>
		<% end %>
		<span style="float:left">
	<%= link_to_function("expand notes",nil, {:style => @expand_style, :id => "piping_class_detail_expand_#{piping_class_detail.id}"}) do |page|
	page["piping_class_detail_notes_#{piping_class_detail.id}"].show
	page["piping_class_detail_expand_#{piping_class_detail.id}"].hide
			end %>
		</span>
		<div id="piping_class_detail_notes_<%="#{piping_class_detail.id}"%>" style="display:none; float:left">
		<%= link_to_function("hide notes",nil, :id => "piping_class_detail_hide_#{piping_class_detail.id}") do |page|
	page["piping_class_detail_notes_#{piping_class_detail.id}"].hide
	page["piping_class_detail_expand_#{piping_class_detail.id}"].show
			end %>
		
<%= render :partial => 'detail_notes', :locals => {:piping_class_detail => piping_class_detail} %>		
		</div>

		
				<span style="float:right">
					<%= link_to_function("(add note)",nil, 
							:id => "piping_class_detail_add_#{piping_class_detail.id}") do |page| 
								page["new_note_#{piping_class_detail.id}"].show
								page["piping_class_detail_add_#{piping_class_detail.id}"].hide
							end %>
				</span>
					<%= form_remote_tag :url => {:action => 'new_note'},
						:html => {:id => "new_note_#{piping_class_detail.id}",
						:style => "display:none",
						:before   => %(Element.show('ajax_loading')), 
						:success => %(Element.hide('ajax_loading'))} do -%>
								<br/>
						<%= text_field_tag('note', nil )%> 
						<%= hidden_field_tag('piping_class_detail_id',  piping_class_detail.id)%>
						<%= submit_tag 'Save' %>
						<%= link_to_function("Cancel",nil) do |page| 
								page["new_note_#{piping_class_detail.id}"].hide
								page["piping_class_detail_add_#{piping_class_detail.id}"].show
							end %>
					<% end %>
			
	</td>
	<td class="bc">
		<% if piping_class_detail.bc9? %>
			<a href="/images/bc9.jpg">BC-9</a>
		<% elsif(piping_class_detail.bc10?) %>
			<a href="/images/bc10.jpg">BC-10</a>
		<% elsif(piping_class_detail.bc11?) %>
			<a href="/images/bc11.jpg">BC-11</a>
		<% end %>
	</td>
<% render :partial => 'detail_component', :locals => {:piping_class_detail => piping_class_detail} %>

<% render :partial => 'detail_valve', :locals => {:piping_class_detail => piping_class_detail} %>



</div>
<% end %>
</table>